/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign6;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  ALTERNATIVE, BADGE_DETAIL, BADGES, CONTACT_BANNER, CONTACT_BUTTON, CONTACT_FORM, DEALER_PHONE, FEATURES, GET_DIRECTIONS, MARKET_REPORT, PHOTO_MODAL, VEHICLE_HISTORY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.assign6\",\"symbols\":[\"ALTERNATIVE\",\"BADGE_DETAIL\",\"BADGES\",\"CONTACT_BANNER\",\"CONTACT_BUTTON\",\"CONTACT_FORM\",\"DEALER_PHONE\",\"FEATURES\",\"GET_DIRECTIONS\",\"MARKET_REPORT\",\"PHOTO_MODAL\",\"VEHICLE_HISTORY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
